title: Realidad Alterna
description: Hub central del proyecto Realidad Alterna / TierraSapiens
theme: minima
markdown: kramdown
# Tienes que hacer este cambio AHORA para corregir la vista local
baseurl: ""