title: TierraSapiens
description: Hub central del proyecto Realidad Alterna / TierraSapiens
theme: minima
markdown: kramdown
url: https://tierrasapiens.github.io/RealidadAlterna/feed.xml
baseurl: /RealidadAlterna